name: Linting & tests

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      # Not failing fast allows all matrix jobs to try & finish even if one fails early
      fail-fast: false
      matrix:
        env:
          - {PYTHON: '3.7', NAME: "Type consistency (mypy)", DEPS: ".[typing]", CMD: "./tools/run-mypy"}
          - {PYTHON: '3.7', NAME: "PEP8 & more (flake8)", DEPS: ".[linting]", CMD: "flake8 zulipterminal/ tests/ setup.py `tools/python_tools.py`"}
          - {PYTHON: '3.6', NAME: "Import order (isort)", DEPS: ".[linting] pytest", CMD: "./tools/run-isort-check"}
          - {PYTHON: '3.6', NAME: "Code formatting (black)", DEPS: ".[linting]", CMD: "black --check zulipterminal/ tests/ setup.py `tools/python_tools.py`"}
    name: Lint - ${{ matrix.env.NAME}}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python version ${{ matrix.env.PYTHON }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.env.PYTHON }}
          cache: 'pip'
          cache-dependency-path: 'setup.py'
      - name: Output Python version
        run: python --version
      - name: Upgrade pip & install wheel
        run: python -m pip install --upgrade pip && python -m pip install wheel
      - name: Install dependencies
        run: pip install ${{ matrix.env.DEPS }}
      - name: Lint
        run: ${{ matrix.env.CMD }}

  pytest:
    strategy:
      # Not failing fast allows all matrix jobs to try & finish even if one fails early
      fail-fast: false
      matrix:
        env:
          - {PYTHON: 3.6, OS: ubuntu-latest, NAME: "CPython 3.6 (ubuntu)"}
          - {PYTHON: 3.7, OS: ubuntu-latest, NAME: "CPython 3.7 (ubuntu)"}
          - {PYTHON: 3.8, OS: ubuntu-latest, NAME: "CPython 3.8 (ubuntu)"}
          - {PYTHON: 3.9, OS: ubuntu-latest, NAME: "CPython 3.9 (ubuntu)", CODECOV: true}
          - {PYTHON: "3.10", OS: ubuntu-latest, NAME: "CPython 3.10 (ubuntu)"}
          - {PYTHON: 'pypy-3.6', OS: ubuntu-latest, NAME: "PyPy 3.6 (ubuntu)"}
          - {PYTHON: 'pypy-3.7', OS: ubuntu-latest, NAME: "PyPy 3.7 (ubuntu)"}
          - {PYTHON: 'pypy-3.8', OS: ubuntu-latest, NAME: "PyPy 3.8 (ubuntu)"}
          - {PYTHON: 'pypy-3.9', OS: ubuntu-latest, NAME: "PyPy 3.9 (ubuntu)"}
          - {PYTHON: 3.9, OS: macos-latest, NAME: "CPython 3.9 (macos)"}
    runs-on: ${{ matrix.env.OS }}
    name: Install & test - ${{ matrix.env.NAME}}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python version ${{ matrix.env.PYTHON }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.env.PYTHON }}
          cache: 'pip'
          cache-dependency-path: 'setup.py'
      - name: Output Python version
        run: python --version
      - name: Upgrade pip & install wheel
        run: python -m pip install --upgrade pip && python -m pip install wheel
      - name: Ensure libxml-related libraries are installed (some pypy versions don't have wheels)
        if: startsWith(matrix.env.PYTHON, 'pypy-')
        run: sudo apt install libxml2-dev libxslt1-dev
      - name: Ensure regular package installs from checkout
        run: pip install .
      - name: Install test dependencies
        run: pip install .[testing]
      - name: Run tests with pytest
        run: pytest --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        # We avoid extra work by just running codecov on one python version
        if: matrix.env.CODECOV
